name: boostsecurity.io
on: 
  push:
    branches:
      - develop
jobs:
  boost-sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Native Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        env:
          BOOST_GIT_MAIN_BRANCH: develop
        with:
          main_branch: develop
          api_token: ${{ secrets.BOOST_API_KEY }}
          registry_module: boostsecurityio/native-scanner
